-- Xoa TOAN BO du lieu (giu nguyen schema, trigger, view, procedure).
-- Chay tren MOI node. Tat FK check de xoa nhanh, khong vuong thu tu.
USE QuanLyToaNha;
SET FOREIGN_KEY_CHECKS = 0;
TRUNCATE TABLE CHI_TIET_HOA_DON;
TRUNCATE TABLE HOA_DON;
TRUNCATE TABLE LUONG_NHAN_VIEN;
TRUNCATE TABLE SU_DUNG_DICH_VU;
TRUNCATE TABLE PHAN_CONG_CONG_VIEC;
TRUNCATE TABLE QUAN_LY_NHAN_VIEN;
TRUNCATE TABLE DANG_KY_DICH_VU;
TRUNCATE TABLE CHI_TIET_HOP_DONG;
TRUNCATE TABLE HOP_DONG_THUE;
TRUNCATE TABLE NHAN_VIEN_CONG_TY;
TRUNCATE TABLE NHAN_VIEN_TOA_NHA;
TRUNCATE TABLE VAN_PHONG;
TRUNCATE TABLE CONG_TY;
TRUNCATE TABLE NGUOI_DUNG;
TRUNCATE TABLE DICH_VU;
TRUNCATE TABLE LOAI_CHI_PHI;
TRUNCATE TABLE VI_TRI_CONG_VIEC;
SET FOREIGN_KEY_CHECKS = 1;
